# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63hatting.proto\"\x07\n\x05\x45mpty\"\x14\n\x04Time\x12\x0c\n\x04time\x18\x01 \x01(\t\"=\n\x12GiveUserAndChannel\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63hannel_name\x18\x02 \x01(\t\"#\n\x0b\x43hannelList\x12\x14\n\x0c\x63hannel_list\x18\x01 \x03(\t\")\n\x11ShowPeopleRequest\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\"$\n\rChannelPeople\x12\x13\n\x0bpeople_list\x18\x01 \x03(\t\"\x1f\n\x0cSuccessOrNot\x12\x0f\n\x07success\x18\x01 \x01(\x08\"a\n\x0b\x43hatRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x63hannel_name\x18\x03 \x01(\t\x12\x10\n\x03\x63md\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_cmd2\xea\x02\n\x08\x43hatting\x12\x1e\n\x0b\x43heckClient\x12\x06.Empty\x1a\x05.Time0\x01\x12\x31\n\x0bMakeChannel\x12\x13.GiveUserAndChannel\x1a\r.SuccessOrNot\x12#\n\x0bShowChannel\x12\x06.Empty\x1a\x0c.ChannelList\x12\x32\n\x0c\x45nterChannel\x12\x13.GiveUserAndChannel\x1a\r.SuccessOrNot\x12\x31\n\x0b\x45xitChannel\x12\x13.GiveUserAndChannel\x1a\r.SuccessOrNot\x12\x37\n\x11ShowChannelPeople\x12\x12.ShowPeopleRequest\x1a\x0e.ChannelPeople\x12$\n\nChatStream\x12\x06.Empty\x1a\x0c.ChatRequest0\x01\x12 \n\x08SendChat\x12\x0c.ChatRequest\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatting_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_TIME']._serialized_start=27
  _globals['_TIME']._serialized_end=47
  _globals['_GIVEUSERANDCHANNEL']._serialized_start=49
  _globals['_GIVEUSERANDCHANNEL']._serialized_end=110
  _globals['_CHANNELLIST']._serialized_start=112
  _globals['_CHANNELLIST']._serialized_end=147
  _globals['_SHOWPEOPLEREQUEST']._serialized_start=149
  _globals['_SHOWPEOPLEREQUEST']._serialized_end=190
  _globals['_CHANNELPEOPLE']._serialized_start=192
  _globals['_CHANNELPEOPLE']._serialized_end=228
  _globals['_SUCCESSORNOT']._serialized_start=230
  _globals['_SUCCESSORNOT']._serialized_end=261
  _globals['_CHATREQUEST']._serialized_start=263
  _globals['_CHATREQUEST']._serialized_end=360
  _globals['_CHATTING']._serialized_start=363
  _globals['_CHATTING']._serialized_end=725
# @@protoc_insertion_point(module_scope)
